services:
  graphdb:
    image: neo4j:latest
    container_name: graphdb
    hostname: graphdb
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    env_file:
      - .env
    networks:
      - default
